# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: sql_database_agent
# Time Created: 2025-02-02 01:11:28


def sql_database_pipeline(connection):
    import pandas as pd
    import sqlalchemy as sql
    
    # Create a connection if needed
    is_engine = isinstance(connection, sql.engine.base.Engine)
    conn = connection.connect() if is_engine else connection

    sql_query = '''
    SELECT timestamp, "Furnace temperature", "Fresh feed flow" 
FROM historical_data;
    '''
    
    return pd.read_sql(sql_query, connection)
    